package x

import de.comahe.i18n4k.Locale
import de.comahe.i18n4k.messages.MessageBundle
import de.comahe.i18n4k.messages.providers.MessagesProvider
import de.comahe.i18n4k.strings.LocalizedString
import kotlin.Array
import kotlin.Int
import kotlin.String

/**
 * Massage constants for bundle 'Bobo'. Generated by i18n4k.
 */
public object Bobo : MessageBundle() {
  /**
   * abc
   */
  public val a_b_c: LocalizedString = getLocalizedString0(0)

  /**
   * abd
   */
  public val a_b_d: LocalizedString = getLocalizedString0(1)

  init {
    registerTranslation(Bobo_en)
    registerTranslation(Bobo_de)
  }
}

/**
 * Translation of message bundle 'Bobo' for locale 'en'. Generated by i18n4k.
 */
private object Bobo_en : MessagesProvider {
  private val _data: Array<String?> = arrayOf(
      "abc",
      "abd")

  public override val locale: Locale = Locale("en")

  public override val size: Int
    get() = _data.size

  public override fun `get`(index: Int): String? = _data[index]
}

/**
 * Translation of message bundle 'Bobo' for locale 'de'. Generated by i18n4k.
 */
private object Bobo_de : MessagesProvider {
  private val _data: Array<String?> = arrayOf(
      "ABC",
      "ABD")

  public override val locale: Locale = Locale("de")

  public override val size: Int
    get() = _data.size

  public override fun `get`(index: Int): String? = _data[index]
}
