import de.comahe.i18n4k.Locale
import de.comahe.i18n4k.messages.MessageBundle
import de.comahe.i18n4k.messages.MessageBundleLocalizedString
import de.comahe.i18n4k.messages.MessageBundleLocalizedStringFactory1
import de.comahe.i18n4k.messages.MessageBundleLocalizedStringFactory2
import de.comahe.i18n4k.messages.MessageBundleLocalizedStringFactory3
import de.comahe.i18n4k.messages.MessageBundleLocalizedStringFactory4
import de.comahe.i18n4k.messages.MessageBundleLocalizedStringFactory5
import de.comahe.i18n4k.messages.providers.MessagesProvider
import kotlin.Array
import kotlin.Int
import kotlin.String
import kotlin.jvm.JvmStatic

/**
 * Massage constants for bundle 'Abba'. Generated by i18n4k.
 */
public object Abba : MessageBundle("Abba", "") {
  /**
   * Number
   */
  @JvmStatic
  public val _1_number_key: MessageBundleLocalizedString = getLocalizedString0("1-number-key", 0)

  /**
   * Hello, World
   */
  @JvmStatic
  public val Hello_World_: MessageBundleLocalizedString = getLocalizedString0("Hello World!", 1)

  /**
   * I ^
   * ^have two
   * circumflexes
   * in the text
   */
  @JvmStatic
  public val Multi_Line_Value: MessageBundleLocalizedString =
      getLocalizedString0("Multi-Line-Value", 2)

  /**
   * Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Phasellus faucibus molestie nisl.
   * Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit
   * mauris vel metus. Pellentesque ipsum. Integer malesuada. Fusce wisi. Nullam dapibus fermentum
   * ipsum. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
   * commodo consequat. Integer rutrum, orci vestibulum ullamcorper ultricies, lacus quam ultricies
   * odio, vitae placerat pede sem sit amet enim. Quisque tincidunt scelerisque libero. Etiam posuere
   * lacus quis dolor. In laoreet, magna id viverra tincidunt, sem odio bibendum justo, vel imperdiet
   * sapien wisi sed libero. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet,
   * consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore
   * magnam aliquam quaerat voluptatem. Pellentesque sapien.
   */
  @JvmStatic
  public val longTextExample: MessageBundleLocalizedString = getLocalizedString0("longTextExample",
      3)

  /**
   * 3rd value: {2}
   */
  @JvmStatic
  public val max_param_3: MessageBundleLocalizedStringFactory3 =
      getLocalizedStringFactory3("max_param-3", 4)

  /**
   * Not all have translations
   */
  @JvmStatic
  public val no_all_have_translations: MessageBundleLocalizedString =
      getLocalizedString0("no-all-have-translations", 5)

  /**
   * Parameter 1: {0}
   */
  @JvmStatic
  public val param_1: MessageBundleLocalizedStringFactory1 = getLocalizedStringFactory1("param_1",
      6)

  /**
   * Parameter 2: {0},{1}
   */
  @JvmStatic
  public val param_2: MessageBundleLocalizedStringFactory2 = getLocalizedStringFactory2("param_2",
      7)

  /**
   * Parameter 3: {0},{1},{2}
   */
  @JvmStatic
  public val param_3: MessageBundleLocalizedStringFactory3 = getLocalizedStringFactory3("param_3",
      8)

  /**
   * Parameter 4: {0},{1},{2},{3}
   */
  @JvmStatic
  public val param_4: MessageBundleLocalizedStringFactory4 = getLocalizedStringFactory4("param_4",
      9)

  /**
   * Parameter 5: {0},{1},{2},{3},{4}
   */
  @JvmStatic
  public val param_5: MessageBundleLocalizedStringFactory5 = getLocalizedStringFactory5("param_5",
      10)

  /**
   * %S%P%T%M%N%L - '{0}' '' '{''}'
   */
  @JvmStatic
  public val special_value: MessageBundleLocalizedString = getLocalizedString0("special-value", 11)

  /**
   * Extraterrestrial 👽
   */
  @JvmStatic
  public val utf_8_value: MessageBundleLocalizedString = getLocalizedString0("utf-8-value", 12)

  /**
   * Special key
   */
  @JvmStatic
  public val _Special_Key_: MessageBundleLocalizedString = getLocalizedString0("~Special#Key~", 13)

  /**
   * Special key 2
   */
  @JvmStatic
  public val _Special__S_P_T_M_N_L_Key2_: MessageBundleLocalizedString =
      getLocalizedString0("~Special-%S%P%T%M%N%L-Key2~", 14)

  init {
    registerTranslation(Abba_en)
    registerTranslation(Abba_en_US)
    registerTranslation(Abba_en_US_texas)
    registerTranslation(Abba_de)
  }
  init {
    registerMessageBundleEntries(_1_number_key, Hello_World_, Multi_Line_Value, longTextExample,
        max_param_3, no_all_have_translations, param_1, param_2, param_3, param_4, param_5,
        special_value, utf_8_value, _Special_Key_, _Special__S_P_T_M_N_L_Key2_)
  }
}

/**
 * Translation of message bundle 'Abba' for locale 'en'. Generated by i18n4k.
 */
private object Abba_en : MessagesProvider {
  @JvmStatic
  private val _data: Array<String?> = arrayOf(
      "Number",
      "Hello, World",
      """
      |I ^
      |^have two
      |circumflexes
      |in the text
      """.trimMargin(),
      "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Phasellus faucibus molestie nisl. Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. Pellentesque ipsum. Integer malesuada. Fusce wisi. Nullam dapibus fermentum ipsum. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Integer rutrum, orci vestibulum ullamcorper ultricies, lacus quam ultricies odio, vitae placerat pede sem sit amet enim. Quisque tincidunt scelerisque libero. Etiam posuere lacus quis dolor. In laoreet, magna id viverra tincidunt, sem odio bibendum justo, vel imperdiet sapien wisi sed libero. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Pellentesque sapien.",
      "3rd value: {2}",
      "Not all have translations",
      "Parameter 1: {0}",
      "Parameter 2: {0},{1}",
      "Parameter 3: {0},{1},{2}",
      "Parameter 4: {0},{1},{2},{3}",
      "Parameter 5: {0},{1},{2},{3},{4}",
      "%S%P%T%M%N%L - '{0}' '' '{''}'",
      "Extraterrestrial 👽",
      "Special key",
      "Special key 2")

  override val locale: Locale = Locale("en")

  override val size: Int
    get() = _data.size

  override fun `get`(index: Int): String? = _data[index]
}

/**
 * Translation of message bundle 'Abba' for locale 'en_US'. Generated by i18n4k.
 */
private object Abba_en_US : MessagesProvider {
  @JvmStatic
  private val _data: Array<String?> = arrayOf(
      null,
      "Hi, World",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null)

  override val locale: Locale = Locale("en",  "US")

  override val size: Int
    get() = _data.size

  override fun `get`(index: Int): String? = _data[index]
}

/**
 * Translation of message bundle 'Abba' for locale 'en_US_texas'. Generated by i18n4k.
 */
private object Abba_en_US_texas : MessagesProvider {
  @JvmStatic
  private val _data: Array<String?> = arrayOf(
      null,
      "Howdy, World",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null)

  override val locale: Locale = Locale("en",  "US",  "texas")

  override val size: Int
    get() = _data.size

  override fun `get`(index: Int): String? = _data[index]
}

/**
 * Translation of message bundle 'Abba' for locale 'de'. Generated by i18n4k.
 */
private object Abba_de : MessagesProvider {
  @JvmStatic
  private val _data: Array<String?> = arrayOf(
      "Nummer",
      "Hallo, Welt!",
      """
      |Ich ^
      |^ habe zwei
      | Zirkumflex
      |im Text
      """.trimMargin(),
      null,
      "3. Wert: {2}",
      "",
      "Parameter 1: {0}",
      "Parameter 2: {0},{1}",
      "Parameter 3: {0},{1},{2}",
      "Parameter 4: {0},{1},{2},{3},",
      "Parameter 5: {0},{1},{2},{3},{4}",
      "%S%P%T%M%N%L - '{0}' '' '{''}'",
      "Außerirdischer 👽",
      "Besonderer Schlüssel",
      "Besonderer Schlüssel 2")

  override val locale: Locale = Locale("de")

  override val size: Int
    get() = _data.size

  override fun `get`(index: Int): String? = _data[index]
}
