== Select formatter

Select a text/message based on the value of the parameter.

xref:general.adoc#formatter_-general[`FORMAT_TYPE`] is `select`

The list elements in xref:general.adoc#formatter_-general[`FORMAT_STYLE`]
form the select cases and corresponding texts.
Where elements without curly braces form the values to compare
and the element with curly braces the text/message to be used.

In general, it could be structured like the following example:

----
VALUE1 {TEXT1} VALUE2 VALUE3 {TEXT2} /VALUE_REGEX/ {TEXT3} other {OTHERWISE_TEXT}
----

* `VALUE*`:
** If a values matches the value of the parameter,
the corresponding text (`TEXT*`) is selected.
** A list of several values for the same text can be given.
** When the parameter matches several values,
the first matching value in the list is used.
* `VALUE_REGEX`
** When the value is prefixed and suffixed by "/",
it is seen as regular repression, e.g. `/([A-Z])\w+/`.
** If the regex matches the value of the parameter,
the corresponding text (`TEXT3`) is selected.
* `TEXT*`:
** The text that is returned by the pattern,
if the value before matches the value of the parameter
** Texts themselves can also contain parameters. So, the parameters can be nested.
* `OTHERWISE_TEXT`
** The keyword `other` matches every value.
** Therefore, if no other value before matches, this text will be selected
** If there is no `OTHERWISE_TEXT` specified and no value matches,
an empty string is returned

Example:

----
{0} has forgotten {1, select, female {her} other {his} } {3, select, one {bag} other {{2} bags} }.
----

Result for [0: Peter, 1: male, 2: 1, 3: one]: +
_Peter has forgotten his bag._


Result for [0: Mary, 1: female, 2: 2, 3: few]: +
_Mary has forgotten her 2 bags._


'''

Back to xref:index.adoc[Formatters]

