package x.y

import de.comahe.i18n4k.Locale
import de.comahe.i18n4k.messages.MessageBundle
import de.comahe.i18n4k.messages.MessageBundleLocalizedString
import de.comahe.i18n4k.messages.providers.MessagesProvider
import kotlin.Array
import kotlin.Int
import kotlin.String
import kotlin.jvm.JvmStatic

/**
 * Massage constants for bundle 'Coolo'. Generated by i18n4k.
 */
public object Coolo : MessageBundle("Coolo", "x.y") {
  /**
   * do that!
   */
  @JvmStatic
  public val to_do_that: MessageBundleLocalizedString = getLocalizedString0("to.do.that", 0)

  /**
   * do this!
   */
  @JvmStatic
  public val to_do_this: MessageBundleLocalizedString = getLocalizedString0("to.do.this", 1)

  init {
    registerTranslation(Coolo_en)
    registerTranslation(Coolo_de)
  }
  init {
    registerMessageBundleEntries(to_do_that, to_do_this)
  }
}

/**
 * Translation of message bundle 'Coolo' for locale 'en'. Generated by i18n4k.
 */
private object Coolo_en : MessagesProvider {
  @JvmStatic
  private val _data: Array<String?> = arrayOf(
      "do that!",
      "do this!")

  public override val locale: Locale = Locale("en")

  public override val size: Int
    get() = _data.size

  public override fun `get`(index: Int): String? = _data[index]
}

/**
 * Translation of message bundle 'Coolo' for locale 'de'. Generated by i18n4k.
 */
private object Coolo_de : MessagesProvider {
  @JvmStatic
  private val _data: Array<String?> = arrayOf(
      "mach jenes!",
      "mach das!!")

  public override val locale: Locale = Locale("de")

  public override val size: Int
    get() = _data.size

  public override fun `get`(index: Int): String? = _data[index]
}
