package x.y

import de.comahe.i18n4k.Locale
import de.comahe.i18n4k.messages.MessageBundle
import de.comahe.i18n4k.messages.providers.MessagesProvider
import de.comahe.i18n4k.strings.LocalizedString
import kotlin.Array
import kotlin.Int
import kotlin.String

/**
 * Massage constants for bundle 'Coolo'. Generated by i18n4k.
 */
public object Coolo : MessageBundle() {
  /**
   * do that!
   */
  public val to_do_that: LocalizedString = getLocalizedString0(0)

  /**
   * do this!
   */
  public val to_do_this: LocalizedString = getLocalizedString0(1)

  init {
    registerTranslation(Coolo_en)
    registerTranslation(Coolo_de)
  }
}

/**
 * Translation of message bundle 'Coolo' for locale 'en'. Generated by i18n4k.
 */
private object Coolo_en : MessagesProvider {
  private val _data: Array<String?> = arrayOf(
      "do that!",
      "do this!")

  public override val locale: Locale = Locale("en")

  public override val size: Int
    get() = _data.size

  public override fun `get`(index: Int): String? = _data[index]
}

/**
 * Translation of message bundle 'Coolo' for locale 'de'. Generated by i18n4k.
 */
private object Coolo_de : MessagesProvider {
  private val _data: Array<String?> = arrayOf(
      "mach jenes!",
      "mach das!!")

  public override val locale: Locale = Locale("de")

  public override val size: Int
    get() = _data.size

  public override fun `get`(index: Int): String? = _data[index]
}
