import de.comahe.i18n4k.Locale
import de.comahe.i18n4k.messages.MessageBundle
import de.comahe.i18n4k.messages.providers.MessagesProvider
import de.comahe.i18n4k.strings.LocalizedString
import de.comahe.i18n4k.strings.LocalizedStringFactory1
import de.comahe.i18n4k.strings.LocalizedStringFactory2
import de.comahe.i18n4k.strings.LocalizedStringFactory3
import de.comahe.i18n4k.strings.LocalizedStringFactory4
import de.comahe.i18n4k.strings.LocalizedStringFactory5
import kotlin.Array
import kotlin.Int
import kotlin.String

/**
 * Massage constants for bundle 'Abba'. Generated by i18n4k.
 */
public object Abba : MessageBundle() {
  /**
   * Number
   */
  public val _1_number_key: LocalizedString = getLocalizedString0(0)

  /**
   * Hello, World
   */
  public val Hello_World_: LocalizedString = getLocalizedString0(1)

  /**
   * I ^
   * ^have two
   * circumflexes
   * in the text
   */
  public val Multi_Line_Value: LocalizedString = getLocalizedString0(2)

  /**
   * 3rd value: {2}
   */
  public val max_param_3: LocalizedStringFactory3 = getLocalizedStringFactory3(3)

  /**
   * Not all have translations
   */
  public val no_all_have_translations: LocalizedStringFactory1 = getLocalizedStringFactory1(4)

  /**
   * Parameter 1: {0}
   */
  public val param_1: LocalizedStringFactory1 = getLocalizedStringFactory1(5)

  /**
   * Parameter 2: {0},{1}
   */
  public val param_2: LocalizedStringFactory2 = getLocalizedStringFactory2(6)

  /**
   * Parameter 3: {0},{1},{2}
   */
  public val param_3: LocalizedStringFactory3 = getLocalizedStringFactory3(7)

  /**
   * Parameter 4: {0},{1},{2},{3}
   */
  public val param_4: LocalizedStringFactory4 = getLocalizedStringFactory4(8)

  /**
   * Parameter 5: {0},{1},{2},{3},{4}
   */
  public val param_5: LocalizedStringFactory5 = getLocalizedStringFactory5(9)

  /**
   * Extraterrestrial 👽
   */
  public val utf_8_value: LocalizedString = getLocalizedString0(10)

  /**
   * Special key
   */
  public val _Specail_Key_: LocalizedString = getLocalizedString0(11)

  init {
    registerTranslation(Abba_en)
    registerTranslation(Abba_de)
  }
}

/**
 * Translation of message bundle 'Abba' for locale 'en'. Generated by i18n4k.
 */
private object Abba_en : MessagesProvider {
  private val _data: Array<String?> = arrayOf(
      "Number",
      "Hello, World",
      "I ^\n^have two\ncircumflexes\nin the text",
      "3rd value: {2}",
      "Not all have translations",
      "Parameter 1: {0}",
      "Parameter 2: {0},{1}",
      "Parameter 3: {0},{1},{2}",
      "Parameter 4: {0},{1},{2},{3}",
      "Parameter 5: {0},{1},{2},{3},{4}",
      "Extraterrestrial 👽",
      "Special key")

  public override val locale: Locale = Locale("en")

  public override val size: Int = _data.size

  public override fun `get`(index: Int): String? = _data[index]
}

/**
 * Translation of message bundle 'Abba' for locale 'de'. Generated by i18n4k.
 */
private object Abba_de : MessagesProvider {
  private val _data: Array<String?> = arrayOf(
      "Nummer",
      "Hallo, Welt!",
      "Ich ^\n^ habe zwei\n Zirkumflex\nim Text",
      "3. Wert: {2}",
      "",
      "Parameter 1: {0}",
      "Parameter 2: {0},{1}",
      "Parameter 3: {0},{1},{2}",
      "Parameter 4: {0},{1},{2},{3},",
      "Parameter 5: {0},{1},{2},{3},{4}",
      "Außerirdischer 👽",
      "Besonderer Schlüssel")

  public override val locale: Locale = Locale("de")

  public override val size: Int = _data.size

  public override fun `get`(index: Int): String? = _data[index]
}
